# Tools/jsbsim-pacejka.py
# Generate JSBSim CORNERING_COEFF tables using a Pacejka-style Magic Formula.

import argparse
import math


PRESETS = {
    "jsbsim-default": {
        "b": 0.06,
        "c": 2.8,
        "d": 0.80,
        "e": 1.03,
    },

    "mooney-nose": {
        "b": 0.06,
        "c": 2.8,
        "d": 0.80,
        "e": 1.03,
    },

    "mooney-main": {
        "b": 0.06,
        "c": 2.8,
        "d": 0.80,
        "e": 1.03,
    },
}


def pacejka(slip_angle_deg, b, c, d, e):
    # Pacejka-style Magic Formula:
    # y = D * sin(C * atan(Bx - E * (Bx - atan(Bx))))
    #
    # JSBSim tire cornering tables use slip angle in degrees.
    x = slip_angle_deg
    bx = b * x

    return d * math.sin(c * math.atan(bx - e * (bx - math.atan(bx))))


def build_angles(max_angle, step):
    # Build a symmetric angle list from -max_angle to +max_angle.
    angles = []
    angle = -max_angle

    while angle <= max_angle + 1e-9:
        angles.append(round(angle, 10))
        angle += step

    if 0.0 not in angles:
        angles.append(0.0)

    return sorted(set(angles))


def generate_table(b, c, d, e, max_angle, step, precision, preset_name):
    print(
        f"<!-- Generated by Tools/jsbsim-pacejka.py preset={preset_name} "
        f"B={b:g} C={c:g} D={d:g} E={e:g} -->"
    )
    print('<table name="CORNERING_COEFF" type="internal">')
    print("    <tableData>")

    for angle in build_angles(max_angle, step):
        if abs(angle) < 1e-9:
            coeff = 0.0
        else:
            coeff = pacejka(angle, b, c, d, e)

        print(f"        {angle:>6.1f} {coeff: .{precision}f}")

    print("    </tableData>")
    print("</table>")


def main():
    parser = argparse.ArgumentParser(
        description="Generate JSBSim CORNERING_COEFF tables using a Pacejka-style Magic Formula."
    )

    parser.add_argument(
        "--preset",
        choices=PRESETS.keys(),
        default="jsbsim-default",
        help="Preset tire curve to generate.",
    )
    parser.add_argument("--b", type=float, default=None,
                        help="Stiffness factor")
    parser.add_argument("--c", type=float, default=None, help="Shape factor")
    parser.add_argument("--d", type=float, default=None,
                        help="Peak friction coefficient")
    parser.add_argument("--e", type=float, default=None,
                        help="Curvature factor")
    parser.add_argument("--max-angle", type=float, default=90.0)
    parser.add_argument("--step", type=float, default=5.0)
    parser.add_argument("--precision", type=int, default=16)

    args = parser.parse_args()

    preset = PRESETS[args.preset]

    b = args.b if args.b is not None else preset["b"]
    c = args.c if args.c is not None else preset["c"]
    d = args.d if args.d is not None else preset["d"]
    e = args.e if args.e is not None else preset["e"]

    if b <= 0:
        raise ValueError("B/stiffness must be greater than 0")

    if c <= 0:
        raise ValueError("C/shape must be greater than 0")

    if d <= 0:
        raise ValueError("D/peak friction must be greater than 0")

    if e < 0:
        raise ValueError("E/curvature must not be negative")

    if args.step <= 0:
        raise ValueError("step must be greater than 0")

    if args.max_angle <= 0:
        raise ValueError("max-angle must be greater than 0")

    if args.precision < 0:
        raise ValueError("precision must not be negative")

    generate_table(
        b=b,
        c=c,
        d=d,
        e=e,
        max_angle=args.max_angle,
        step=args.step,
        precision=args.precision,
        preset_name=args.preset,
    )


if __name__ == "__main__":
    main()
